inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'lib/pg_power/**/*'
Style/Documentation:
  Enabled: true
  Exclude:
    - 'app/models/core/**/*'
Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'lib/**/*'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
RSpec/MultipleExpectations:
  Enabled: true
  Exclude:
    - 'spec/**/*'
RSpec/AnyInstance:
  Enabled: true
  Exclude:
    - 'spec/**/*'


