inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
RSpec/MultipleExpectations:
  Enabled: true
  Exclude:
    - 'spec/**/*'


