config: &config
  cdn:
    url: 'https://example.com'
  access:
    duration:
      api: 3600 # 3600 seconds in 1 hour
  allowed_images:
    - image/jpg
    - image/jpeg
    - image/png
test:
  <<: *config
development:
  <<: *config
production:
  <<: *config
