default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: public, core

development:
  <<: *default
  database: pigeon_api_development
test:
  <<: *default
  database: pigeon_api_test
production:
  <<: *default
  database: pigeon_api_production
  username: pigeon_api
  password: <%= ENV['PIGEON_API_DATABASE_PASSWORD'] %>
